### ISSUE TITLE
Twig 3 compatibility

### ISSUE THREAD

**Issue by KazuAlex** [jdecool/TwigConstantAccessorBundle#27]
Can't install on symfony with Twig >= 3.0

I have not tested it. I don't know if something is broken.

I will try to make necessary changes later unless if someone do it before me.

**Comment by jdecool** [comment]
Hi @KazuAlex 

Thanks for your feed back.

I release a new version `1.6.0` that support Twig 3.x

**Comment by KazuAlex** [comment]
Yes i see it. Nice job, thank you
